package simularmoviment;
import java.awt.Color;
import java.awt.Graphics;
import java.util.ArrayList;
import java.util.List;


public class Panell extends javax.swing.JPanel implements Runnable {

    private int hor = this.getWidth() / 2;
    private Thread fill;
    List<TocarLateralesListener> oients = new ArrayList();
    
    public Panell() {
        initComponents();
        fill = new Thread(this);
        
    }

      public void addTocarLateralesListener(TocarLateralesListener o) {
        oients.add(o);
    }
    
    @Override
    public void paint(Graphics g) {
        g.setColor(this.getBackground());
        g.fillRect(0, 0, this.getWidth(), this.getHeight());
        g.setColor(Color.ORANGE);
        g.fillOval(hor, getHeight() / 2, 30, 30);
    }

    public void iniciar() {
        fill.start();
    }

    public void finalitzar() {
        fill.resume();
    }

    public int getHor() {
        return hor;
    }

    @Override
    public void run() {
        try {
            while (true) {
                while (hor < getWidth() - 30) {
                    Thread.sleep(50);
                    hor += 10;
                    repaint();
                }
                
                    TocarLateralesEvent tle1 = new TocarLateralesEvent(this);
                    for (TocarLateralesListener oient : oients) {
                        oient.modificarColor(tle1);
                    }
                
                while (hor > 0) {
                    Thread.sleep(50);
                    hor -= 10;
                    repaint();
                }
                
                    TocarLateralesEvent tle2 = new TocarLateralesEvent(this);
                    for (TocarLateralesListener oient : oients) {
                        oient.modificarColor(tle2);
                    }
                
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(102, 255, 102));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
